version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  build: # This is our first job.
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/circle-ci-demo
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting